---
- name: Install Apache
  hosts: all
  become: true

  vars:
    apache_package: apache2
    apache_service: apache2

  handlers:
    - name: restart apache
      service:
        name: "{{ apache_service }}"
        state: restarted

  pre_tasks:
    - name: Override Apache vars for Red Hat
      set_fact:
        apache_package: httpd
        apache_service: httpd
      when: ansible_os_family == 'RedHat'

  tasks:
    - name: Install APache
      package:
        name: "{{ apache_package }}"
        state: present

    - name: Copy a web page
      copy:
        content: |
          <html>
          <head><title>Hello World!</title></head>
          <body>Hello World</body>
          </html>
        dest: "/var/www/html/index.html"
        mode: 0755
      notify: restart apache

    - name: Start/enable Apache
      service:
        name: "{{ apache_service }}"
        enabled: true
        state: started
